export { default as GeneralSettingsSection } from "./GeneralSettingsSection";
export { default as ContactDetailsSection } from "./ContactDetailsSection";
export { default as AboutSection } from "./AboutSection";
export { default as VideoTutorialsSection } from "./VideoTutorialsSection";
export { default as JourneyTimelineSection } from "./JourneyTimelineSection";
export { default as ScholarshipTimelineSection } from "./ScholarshipTimelineSection";
export { default as ScholarshipDetailsSection } from "./ScholarshipDetailsSection";
export { default as EligibilitySection } from "./EligibilitySection";
export { default as FAQSection } from "./FAQSection";
export { default as GallerySection, type GalleryImageItem } from "./GallerySection";
export { default as PartnersSection, type PartnerOrganization } from "./PartnersSection";
export { default as PartnerMessagesSection, type PartnerMessageItem } from "./PartnerMessagesSection";
export { default as ExamCentersSection, type ExamCenterItem } from "./ExamCentersSection";
export { default as DownloadsSection, type DownloadItem } from "./DownloadsSection";
export { default as PaymentConfigSection } from "./PaymentConfigSection";