import type { College, ScholarshipItem, EducationNewsItem } from "@/services/api";

export const mockFeaturedColleges: College[] = [
  {
    id: 1,
    name: "Tribhuvan University",
    image_url: "https://placehold.co/600x400/2563eb/ffffff?text=TU",
    banner_url: "https://placehold.co/600x400/2563eb/ffffff?text=Tribhuvan+University",
    rating: 4.5,
    type: "Public",
    location: "Kathmandu, Bagmati",
    affiliation: "University Grants Commission",
    website: "https://tu.edu.np",
    description: "Nepal's oldest and largest university.",
    featured: true,
  },
  {
    id: 2,
    name: "Kathmandu University",
    image_url: "https://placehold.co/600x400/059669/ffffff?text=KU",
    banner_url: "https://placehold.co/600x400/059669/ffffff?text=Kathmandu+University",
    rating: 4.3,
    type: "Private",
    location: "Dhulikhel, Kavrepalanchok",
    affiliation: "University Grants Commission",
    website: "https://ku.edu.np",
    description: "Leading private university in Nepal.",
    featured: true,
  },
  {
    id: 3,
    name: "Pokhara University",
    image_url: "https://placehold.co/600x400/7c3aed/ffffff?text=PU",
    banner_url: "https://placehold.co/600x400/7c3aed/ffffff?text=Pokhara+University",
    rating: 4.1,
    type: "Public",
    location: "Pokhara, Gandaki",
    affiliation: "University Grants Commission",
    website: "https://pu.edu.np",
    description: "University focused on quality education in western Nepal.",
    featured: true,
  },
  {
    id: 4,
    name: "Purbanchal University",
    image_url: "https://placehold.co/600x400/dc2626/ffffff?text=PEU",
    banner_url: "https://placehold.co/600x400/dc2626/ffffff?text=Purbanchal+University",
    rating: 3.9,
    type: "Public",
    location: "Biratnagar, Koshi",
    affiliation: "University Grants Commission",
    website: "https://pu.edu.np",
    description: "University serving eastern Nepal.",
    featured: true,
  },
];

export const mockScholarships: ScholarshipItem[] = [
  {
    id: 1,
    title: "Full Ride Merit Scholarship",
    provider: "Tribhuvan University",
    location: "Kathmandu",
    amount: "100% Tuition",
    deadline: "Aug 15, 2026",
    eligibility: "Bachelor (+2 Sci: 2.8+ GPA)",
    scholarship_type: "MERIT-BASED",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
    isFeatured: true,
    start_date: "2026-06-01",
    end_date: "2026-08-15",
  },
  {
    id: 2,
    title: "STEM Excellence Award",
    provider: "Kathmandu University",
    location: "Kavrepalanchok",
    amount: "75% Tuition",
    deadline: "Sep 10, 2026",
    eligibility: "Master (STEM field, 3.5+ GPA)",
    scholarship_type: "MERIT-BASED",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=600&auto=format&fit=crop",
    isFeatured: true,
    start_date: "2026-07-01",
    end_date: "2026-09-10",
  },
  {
    id: 3,
    title: "Community Service Scholarship",
    provider: "Pokhara University",
    location: "Gandaki",
    amount: "NPR 200,000",
    deadline: "Oct 01, 2026",
    eligibility: "Bachelor (500+ hrs community service)",
    scholarship_type: "NEED-BASED",
    image: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?q=80&w=600&auto=format&fit=crop",
    isFeatured: true,
    start_date: "2026-06-15",
    end_date: "2026-10-01",
  },
  {
    id: 4,
    title: "International Student Grant",
    provider: "Tribhuvan University",
    location: "Bagmati",
    amount: "50% Tuition",
    deadline: "Nov 15, 2026",
    eligibility: "Master (International students)",
    scholarship_type: "GRANT",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=600&auto=format&fit=crop",
    isFeatured: true,
    start_date: "2026-08-01",
    end_date: "2026-11-15",
  },
];

export const mockExams: any[] = [
  {
    id: 1,
    title: "Bachelor of Medicine Entrance Exam 2026",
    board: "Medical Education Commission",
    level: "Bachelor",
    type: "Entrance",
    exam_date: "2026-09-15",
    form_deadline: "2026-08-20",
    status: "open",
    highlights: ["300 seats", "MCQ format", "Negative marking"],
    institution_logo: "https://placehold.co/48x48/2563eb/ffffff?text=MEC",
    institution_name: "Medical Education Commission",
    location: "Kathmandu",
  },
  {
    id: 2,
    title: "IOE Pulchowk Entrance Exam",
    board: "Institute of Engineering",
    level: "Bachelor",
    type: "Entrance",
    exam_date: "2026-09-20",
    form_deadline: "2026-08-25",
    status: "open",
    highlights: ["Highly competitive", "PCM based", "600 seats"],
    institution_logo: "https://placehold.co/48x48/059669/ffffff?text=IOE",
    institution_name: "Institute of Engineering",
    location: "Lalitpur",
  },
  {
    id: 3,
    title: "NEB Grade XII Supplementary Exam",
    board: "National Examination Board",
    level: "+2",
    type: "Supplementary",
    exam_date: "2026-10-05",
    form_deadline: "2026-09-10",
    status: "upcoming",
    highlights: ["All streams", "Retake opportunity"],
    institution_logo: "https://placehold.co/48x48/7c3aed/ffffff?text=NEB",
    institution_name: "National Examination Board",
    location: "Kathmandu",
  },
  {
    id: 4,
    title: "Loksewa Public Service Commission Exam",
    board: "Public Service Commission",
    level: "General",
    type: "Civil Service",
    exam_date: "2026-11-01",
    form_deadline: "2026-09-30",
    status: "upcoming",
    highlights: ["Multiple levels", "Written + Interview"],
    institution_logo: "https://placehold.co/48x48/dc2626/ffffff?text=PSC",
    institution_name: "Public Service Commission",
    location: "Kathmandu",
  },
];

export const mockNewsArticles: EducationNewsItem[] = [
  {
    id: 1,
    category: "Admission",
    title: "Tribhuvan University Announces Fall 2026 Admission Schedule",
    excerpt: "TU has released the admission calendar for undergraduate programs starting September 2026.",
    content: "Tribhuvan University has officially announced the admission schedule for the fall semester of 2026. Applications open on August 20 and close on September 10.",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=600&auto=format&fit=crop",
    author: "StudSphere Team",
    date: "2026-08-07",
    readTime: "3 min read",
    tags: ["admission", "TU", "fall 2026"],
    slug: "tu-fall-2026-admission",
  },
  {
    id: 2,
    category: "Scholarship",
    title: "New Government Scholarships for Engineering Students",
    excerpt: "The government has allocated 500 new scholarships for engineering students in public universities.",
    content: "Ministry of Education has announced 500 full-ride scholarships for students pursuing engineering degrees at government universities.",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=600&auto=format&fit=crop",
    author: "Editorial",
    date: "2026-08-05",
    readTime: "4 min read",
    tags: ["scholarship", "engineering", "government"],
    slug: "govt-engineering-scholarships-2026",
  },
  {
    id: 3,
    category: "Exam",
    title: "IOE Entrance Exam Pattern Changed for 2026",
    excerpt: "Institute of Engineering revises entrance exam format with new negative marking scheme.",
    content: "IOE has introduced a revised exam pattern for 2026 with negative marking for incorrect answers.",
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=600&auto=format&fit=crop",
    author: "StudSphere Team",
    date: "2026-08-03",
    readTime: "2 min read",
    tags: ["exam", "IOE", "entrance"],
    slug: "ioe-entrance-pattern-2026",
  },
  {
    id: 4,
    category: "News",
    title: "Nepal Ranks Higher in South Asian Education Index",
    excerpt: "Nepal's education system has shown significant improvement in the latest South Asian rankings.",
    content: "According to the latest South Asian Education Index, Nepal has moved up 3 positions in overall education quality rankings.",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=600&auto=format&fit=crop",
    author: "Editorial",
    date: "2026-08-01",
    readTime: "5 min read",
    tags: ["news", "ranking", "education"],
    slug: "nepal-education-ranking-2026",
  },
];

export const mockEvents: any[] = [
  {
    id: 1,
    title: "Tech Fest Kathmandu 2026",
    tag: "TECH",
    closeText: "Annual Tech Festival",
    logo: "https://placehold.co/48x48/2563eb/ffffff?text=TF",
    location: "Kathmandu University",
    chips: ["Hackathon", "Workshops", "Networking"],
    schedule: "Sep 15-17, 2026",
    enrolled: "500+ Registered",
    icon: "🏆",
    bottomPill: "Free Entry",
    bottomPillClass: "bg-green-50 text-green-700",
  },
  {
    id: 2,
    title: "Annual Science Conference",
    tag: "SCIENCE",
    closeText: "Research Showcase",
    logo: "https://placehold.co/48x48/059669/ffffff?text=SC",
    location: "Tribhuvan University",
    chips: ["Presentations", "Panel Discussion", "Awards"],
    schedule: "Oct 05-06, 2026",
    enrolled: "300+ Registered",
    icon: "🔬",
    bottomPill: "NPR 500",
    bottomPillClass: "bg-blue-50 text-blue-700",
  },
  {
    id: 3,
    title: "Career Fair Nepal 2026",
    tag: "CAREER",
    closeText: "Job & Internship Fair",
    logo: "https://placehold.co/48x48/7c3aed/ffffff?text=CF",
    location: "Bhattarai Convention Center",
    chips: ["50+ Companies", "Walk-in Interviews", "Resume Review"],
    schedule: "Nov 10, 2026",
    enrolled: "1000+ Registered",
    icon: "💼",
    bottomPill: "Free Entry",
    bottomPillClass: "bg-green-50 text-green-700",
  },
  {
    id: 4,
    title: "Startup Week Pokhara",
    tag: "STARTUP",
    closeText: "Entrepreneurship Event",
    logo: "https://placehold.co/48x48/dc2626/ffffff?text=SW",
    location: "Pokhara University",
    chips: ["Pitch Competition", "Mentorship", "Funding"],
    schedule: "Dec 01-03, 2026",
    enrolled: "200+ Registered",
    icon: "🚀",
    bottomPill: "NPR 200",
    bottomPillClass: "bg-amber-50 text-amber-700",
  },
];

export const mockTestimonials: Array<{
  id: number;
  user_name: string;
  rating: number;
  experience: string;
  role?: string;
}> = [
  {
    id: 1,
    user_name: "Aarav Sharma",
    rating: 5,
    experience: "StudSphere helped me find the perfect university for my engineering degree. The comparison tools made my decision so much easier!",
    role: "B.Tech Student, KU",
  },
  {
    id: 2,
    user_name: "Sita Thapa",
    rating: 4,
    experience: "The scholarship finder saved me hours of research. I found and applied to 3 scholarships through this platform.",
    role: "MBA Student, TU",
  },
  {
    id: 3,
    user_name: "Ram Bahadur Kunwar",
    rating: 5,
    experience: "From choosing the right college to preparing for entrance exams, StudSphere was my go-to resource throughout the process.",
    role: "MBBS Student, MEC",
  },
  {
    id: 4,
    user_name: "Priya Magar",
    rating: 4,
    experience: "The exam announcements kept me updated on every deadline. I never missed an application because of StudSphere notifications.",
    role: "BCA Graduate, PU",
  },
  {
    id: 5,
    user_name: "Bikash Rai",
    rating: 5,
    experience: "Excellent platform for students in Nepal. The college reviews and ratings helped me choose a college that matched my expectations.",
    role: "BBA Student, KU",
  },
];
