import { Exam } from './types';

export const MOCK_EXAMS: Exam[] = [
  {
    id: "ioe-entrance-2081",
    institution: "Tribhuvan University",
    verified: true,
    location: "Pulchowk, Lalitpur",
    affiliation: "TU - IOE",
    website: "ioe.edu.np",
    logo: "https://placehold.co/64x64/0000FF/ffffff?text=IOE",
    title: "IOE BE/B.Arch Entrance 2081",
    tags: [
      { text: "Ongoing", icon: "flame", type: "alert" },
      { text: "Offline", icon: "building", type: "default" },
      { text: "National", icon: "globe", type: "default" },
    ],
    deadline: "Jestha 5, 2082",
    eligibility: "+2 Science (Min 50%)",
    whatsapp: "#",
    viber: "#",
    status: "Ongoing",
    examDate: "Jestha 15, 2082",
    nepaliDate: "Jestha 15, 2082",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cee-medical-2081",
    institution: "Medical Education Commission",
    verified: true,
    location: "Kathmandu",
    affiliation: "MEC",
    website: "mec.gov.np",
    logo: "https://placehold.co/64x64/00a844/ffffff?text=MEC",
    title: "Common Entrance (CEE) for Medical 2081",
    tags: [
      { text: "Ongoing", icon: "flame", type: "alert" },
      { text: "Offline", icon: "building", type: "default" },
    ],
    deadline: "Jestha 30, 2082",
    eligibility: "+2 Science (Min 50%)",
    whatsapp: "#",
    viber: "#",
    status: "Ongoing",
    examDate: "Asar 10, 2082",
    nepaliDate: "Asar 10, 2082",
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cmat-tu-2081",
    institution: "Tribhuvan University",
    verified: true,
    location: "Kirtipur, Kathmandu",
    affiliation: "TU - FOM",
    website: "tu.edu.np",
    logo: "https://placehold.co/64x64/8476F1/ffffff?text=TU",
    title: "CMAT Entrance (Management) 2081",
    tags: [
      { text: "Upcoming", icon: "trending-up", type: "warning" },
      { text: "Offline", icon: "building", type: "default" },
    ],
    deadline: "Bhadra 15, 2082",
    eligibility: "+2 Any Stream (Min 45%)",
    whatsapp: "#",
    viber: "#",
    status: "Upcoming",
    examDate: "Bhadra 2082",
    nepaliDate: "Bhadra 2082",
    imageUrl: "https://images.unsplash.com/photo-1454165833767-1316b344249a?auto=format&fit=crop&w=800&q=80",
  },
];
