import { Exam } from './types';

export const MOCK_EXAMS: Exam[] = [
  {
    id: "1",
    institution: "Kist College",
    verified: true,
    location: "Kathmandu",
    affiliation: "NEB Affiliated",
    website: "kist.edu.np",
    logo: "https://kist.edu.np/resources/assets/img/logo_small.jpg",
    title: "+2 Science Entrance Exam",
    tags: [
      { text: "Limited Seats", icon: "flame", type: "alert" },
      { text: "Online", icon: "monitor", type: "default" },
      { text: "National", icon: "globe", type: "default" },
    ],
    deadline: "04 Jan 2026",
    eligibility: "SEE Passed (Min 2.0 GPA)",
    whatsapp: "#",
    viber: "#",
    status: "Ongoing",
    examDate: "Jestha 15, 2082",
    nepaliDate: "Jestha 15, 2082",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "2",
    institution: "St. Xavier's College",
    verified: true,
    location: "Maitighar",
    affiliation: "NEB Affiliated",
    website: "sxc.edu.np",
    logo: "https://placehold.co/64x64/1e3a8a/ffffff?text=SXC",
    title: "+2 Science Entrance Exam",
    tags: [
      { text: "High Demand", icon: "trending-up", type: "warning" },
      { text: "In-Person", icon: "building", type: "default" },
    ],
    deadline: "10 Jul 2026",
    eligibility: "SEE Passed (Min 3.6 GPA)",
    whatsapp: "#",
    viber: "#",
    status: "Ongoing",
    examDate: "Asar 10, 2082",
    nepaliDate: "Asar 10, 2082",
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "3",
    institution: "Trinity Int'l College",
    verified: true,
    location: "Dillibazar",
    affiliation: "NEB Affiliated",
    website: "trinity.edu.np",
    logo: "https://www.trinity.edu.np/assets/backend/uploads/Logo/trinity%20college%20logo.jpg",
    title: "A-Level Entrance 2026",
    tags: [
      { text: "Scholarships", icon: "award", type: "success" },
      { text: "Hybrid", icon: "monitor", type: "default" },
    ],
    deadline: "25 Aug 2026",
    eligibility: "SEE Passed (Min 2.8 GPA)",
    whatsapp: "#",
    viber: "#",
    status: "Upcoming",
    examDate: "Bhadra 2082",
    nepaliDate: "Bhadra 2082",
    imageUrl: "https://images.unsplash.com/photo-1454165833767-1316b344249a?auto=format&fit=crop&w=800&q=80",
  },
];
