import { ExamDetails } from "@/app/entrance/types";

export const MOCK_EXAM_DETAILS: Record<string, ExamDetails> = {
  "ioe-entrance-2081": {
    id: "ioe-entrance-2081",
    title: "IOE BE/B.Arch Entrance 2081",
    university: "Tribhuvan University",
    faculty: "Institute of Engineering",
    status: "Ongoing",
    examDate: "Jestha 15, 2082",
    nepaliDate: "Jestha 15, 2082",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80",
    registrationStart: "Chaitra 1, 2081",
    registrationEnd: "Jestha 5, 2082",
    examLevel: "National Level",
    duration: "2 Hours",
    questionType: "Multiple Choice (MCQ)",
    description: "IOE Entrance Examination is conducted by the Institute of Engineering (IOE), Tribhuvan University for admission into BE and B.Arch programs across its constituent and affiliated campuses including Pulchowk, Thapathali, Purwanchal, and Paschimanchal campuses.",
    conductingBody: "Institute of Engineering (IOE), Tribhuvan University",
    examFrequency: "Once a year",
    examMode: "Offline (OMR Based)",
    applicationFee: "NPR 3,500",
    foreignFee: "NPR 7,000",
    applicationSteps: [
      { title: "Fee Payment", description: "Pay the examination fee through eSewa, Khalti, ConnectIPS, or designated bank branches. Regular applicants: NPR 3,500 | Foreign applicants: NPR 7,000." },
      { title: "Online Registration", description: "Visit the IOE admission portal (ioe.edu.np) and fill in personal details, academic records, and upload a passport-size photograph." },
      { title: "Document Verification & Submission", description: "Upload scanned copies of SEE, +2 transcripts, citizenship certificate, and character certificate. Submit the form and print the confirmation page." },
    ],
    eligibility: [
      { title: "Academic Qualification", description: "Must have passed 10+2 or equivalent with Physics, Chemistry, Mathematics, and English as core subjects." },
      { title: "Minimum Marks Requirement", description: "Must have secured a minimum of 50% marks in aggregate in +2 or equivalent. Must have at least 'C+' grade in Physics, Chemistry, and Mathematics." },
      { title: "Nationality", description: "Nepalese citizens and foreign nationals are eligible. Foreign candidates must meet additional documentation requirements including equivalence certificate from NEB." },
    ],
    examPattern: [
      { label: "Total Questions", value: "120 MCQs" },
      { label: "Total Marks", value: "120" },
      { label: "Duration", value: "2 Hours" },
      { label: "Marking Scheme", value: "+1 Correct, 0 Incorrect (No Negative)" },
    ],
    subjectMarks: [
      { subject: "Mathematics", marks: 40 },
      { subject: "Physics", marks: 30 },
      { subject: "Chemistry", marks: 25 },
      { subject: "English", marks: 15 },
      { subject: "General Aptitude", marks: 10 },
    ],
    modelSets: [
      { title: "IOE Official Model Question 2080", size: "1.8 MB", description: "Complete 120 Questions with Blueprint" },
      { title: "IOE Entrance 2080 Past Paper", size: "2.5 MB", description: "With Answer Keys and Solutions" },
    ],
    courses: ["BE Civil", "BE Computer", "BE Electronics", "BE Electrical", "BE Mechanical", "B.Arch"],
    admissionSteps: [
      { title: "Result Publication", description: "IOE publishes the merit list based on entrance exam scores on the official website." },
      { title: "Campus & Program Selection", description: "Candidates select their preferred campuses and programs online based on their rank." },
      { title: "Admission Confirmation", description: "Visit the allotted campus with original documents, pay the first semester fees, and confirm admission." },
    ],
    admitCardInfo: "The IOE admit card is mandatory for exam entry. Download it from the IOE admission portal after the release date. Ensure all details are correct before printing.",
    upcomingDates: [
      { date: "Chaitra 1, 2081 - Jestha 5, 2082", event: "IOE Entrance 2081 Registration", status: "Ongoing" },
      { date: "Jestha 15, 2082", event: "IOE Entrance Examination Date" },
    ],
    pastDates: [
      { date: "Ashwin 15, 2080", event: "IOE Entrance 2080 Examination" },
      { date: "Bhadra 1 - 25, 2080", event: "IOE Entrance 2080 Registration" },
    ],
    faqs: [
      { question: "Can I apply for both BE and B.Arch in the same form?", answer: "Yes, you can apply for both programs. However, B.Arch requires an additional drawing test which is conducted separately." },
      { question: "Is there negative marking in IOE Entrance?", answer: "No, there is no negative marking in the IOE Entrance Examination. Each correct answer carries 1 mark." },
      { question: "What is the application fee for IOE Entrance?", answer: "The application fee is NPR 3,500 for Nepalese students and NPR 7,000 for foreign students." },
      { question: "Which campuses are covered under IOE Entrance?", answer: "IOE Entrance covers all constituent campuses (Pulchowk, Thapathali, Purwanchal, Paschimanchal) and affiliated colleges under TU." },
    ],
  },
  "cee-medical-2081": {
    id: "cee-medical-2081",
    title: "Common Entrance (CEE) for Medical 2081",
    university: "Medical Education Commission",
    faculty: "Medical & Health Sciences",
    status: "Ongoing",
    examDate: "Asar 10, 2082",
    nepaliDate: "Asar 10, 2082",
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    registrationStart: "Baisakh 15, 2082",
    registrationEnd: "Jestha 30, 2082",
    examLevel: "National Level",
    duration: "3 Hours",
    questionType: "Multiple Choice (MCQ)",
    description: "Common Entrance Examination (CEE) for Medical is conducted by the Medical Education Commission (MEC) for admission into MBBS, BDS, and other undergraduate medical programs across all medical colleges in Nepal.",
    conductingBody: "Medical Education Commission (MEC), Nepal",
    examFrequency: "Once a year",
    examMode: "Offline (OMR Based)",
    applicationFee: "NPR 4,000",
    foreignFee: "NPR 8,000",
    applicationSteps: [
      { title: "Fee Payment", description: "Pay the examination fee through eSewa, Khalti, ConnectIPS, or bank voucher. Nepalese students: NPR 4,000 | Foreign students: NPR 8,000." },
      { title: "Profile Creation", description: "Register with your valid email ID, mobile number, and the transaction number from your fee payment to create an account on the MEC portal." },
      { title: "Document Upload & Submission", description: "Fill in personal and academic details. Upload scanned passport-size photo, signature, citizenship/passport, and +2 transcript. Submit and download the confirmation page." },
    ],
    eligibility: [
      { title: "Academic Qualification", description: "Must have passed 10+2 Science (or equivalent) with Physics, Chemistry, and Biology as core subjects." },
      { title: "Minimum Marks Requirement", description: "Must have secured a minimum of 50% marks in aggregate or minimum 'C+' grade in each core subject (Physics, Chemistry, Biology) and 'C' in other subjects." },
      { title: "Nationality", description: "Both Nepalese and Foreign Nationals are eligible to apply. Foreign candidates have separate reservation quotas and fee structures." },
    ],
    examPattern: [
      { label: "Total Questions", value: "200 MCQs" },
      { label: "Total Marks", value: "200" },
      { label: "Duration", value: "3 Hours" },
      { label: "Marking Scheme", value: "+1 Correct, -0.25 Incorrect" },
    ],
    subjectMarks: [
      { subject: "Zoology", marks: 40 },
      { subject: "Botany", marks: 40 },
      { subject: "Chemistry", marks: 50 },
      { subject: "Physics", marks: 50 },
      { subject: "MAT (Mental Agility Test)", marks: 20 },
    ],
    modelSets: [
      { title: "Official MEC Sample Paper 2080", size: "2.4 MB", description: "Complete 200 Questions" },
      { title: "CEE Medical 2080 Past Paper", size: "3.1 MB", description: "With Answer Keys" },
    ],
    courses: ["MBBS", "BDS", "B.Sc Nursing", "BAMS", "B.Pharm", "BPH"],
    admissionSteps: [
      { title: "Merit List Publication", description: "MEC publishes a central merit list based on the entrance exam scores." },
      { title: "Priority Selection (Matching)", description: "Candidates select their preferred colleges and courses online based on their rank." },
      { title: "College Admission", description: "Once matched, students visit the respective college to verify documents and pay fees." },
    ],
    admitCardInfo: "The CEE admit card is a mandatory document. Candidates will not be allowed inside the exam hall without it. Print your admit card in color and ensure your photograph is clearly visible.",
    upcomingDates: [
      { date: "Baisakh 15 - Jestha 30, 2082", event: "CEE Medical 2081 Registration", status: "Ongoing" },
      { date: "Asar 10, 2082", event: "CEE Medical Entrance Examination Date" },
    ],
    pastDates: [
      { date: "Jestha 20, 2081", event: "CEE Medical 2080 Examination" },
      { date: "Chaitra 1 - 25, 2080", event: "CEE Medical 2080 Registration" },
    ],
    faqs: [
      { question: "Is there any age limit to apply for CEE Medical?", answer: "No, there is no age limit specified by the Medical Education Commission for appearing in CEE Medical." },
      { question: "From where can I download the CEE admit card?", answer: "You can download the admit card from the official MEC portal at entrance.mec.gov.np after the release date." },
      { question: "What is the application fee of CEE Medical?", answer: "The application fee is NPR 4,000 for Nepalese students and NPR 8,000 for foreign students." },
      { question: "Does MEC offer master's courses through CEE?", answer: "No, CEE is specifically for undergraduate programs. Master's level entrance exams are conducted separately as MECEE-PG." },
    ],
  },
  "cmat-tu-2081": {
    id: "cmat-tu-2081",
    title: "CMAT Entrance (Management) 2081",
    university: "Tribhuvan University",
    faculty: "Faculty of Management",
    status: "Upcoming",
    examDate: "Bhadra 2082",
    nepaliDate: "Bhadra 2082",
    imageUrl: "https://images.unsplash.com/photo-1454165833767-1316b344249a?auto=format&fit=crop&w=800&q=80",
    registrationStart: "Shrawan 1, 2082",
    registrationEnd: "Bhadra 15, 2082",
    examLevel: "National Level",
    duration: "2 Hours",
    questionType: "Multiple Choice (MCQ)",
    description: "CMAT (Common Management Admission Test) is conducted by Tribhuvan University, Faculty of Management for admission into BBA, BBM, BBS, and other management programs across TU constituent and affiliated campuses.",
    conductingBody: "Faculty of Management, Tribhuvan University",
    examFrequency: "Once a year",
    examMode: "Offline (OMR Based)",
    applicationFee: "NPR 3,000",
    foreignFee: "NPR 6,000",
    applicationSteps: [
      { title: "Fee Payment", description: "Pay the examination fee through eSewa, Khalti, ConnectIPS, or designated bank branches. Regular applicants: NPR 3,000 | Late applicants: NPR 4,500." },
      { title: "Online Registration", description: "Visit the TU FOM admission portal and fill in personal details, academic records, and upload a passport-size photograph." },
      { title: "Document Upload & Submission", description: "Upload scanned copies of SEE, +2 transcripts, citizenship certificate, and character certificate. Submit the form and print the confirmation page." },
    ],
    eligibility: [
      { title: "Academic Qualification", description: "Must have passed 10+2 or equivalent in any stream (Science, Management, Humanities) from a recognized board." },
      { title: "Minimum Marks Requirement", description: "Must have secured a minimum CGPA of 2.0 or 45% marks in aggregate in +2 or equivalent examination." },
      { title: "Nationality", description: "Nepalese citizens and foreign nationals are eligible. Foreign candidates must provide equivalence certificate from NEB." },
    ],
    examPattern: [
      { label: "Total Questions", value: "100 MCQs" },
      { label: "Total Marks", value: "100" },
      { label: "Duration", value: "2 Hours" },
      { label: "Marking Scheme", value: "+1 Correct, 0 Incorrect (No Negative)" },
    ],
    subjectMarks: [
      { subject: "Verbal Ability", marks: 20 },
      { subject: "Quantitative Ability", marks: 25 },
      { subject: "Logical Reasoning", marks: 25 },
      { subject: "General Awareness", marks: 15 },
      { subject: "Computer Knowledge", marks: 15 },
    ],
    modelSets: [
      { title: "CMAT Official Model Question 2080", size: "1.5 MB", description: "Complete 100 Questions with Blueprint" },
      { title: "CMAT 2080 Past Paper", size: "2.0 MB", description: "With Answer Keys" },
    ],
    courses: ["BBA", "BBM", "BBS", "BIM", "BHM", "BBS-CSIT"],
    admissionSteps: [
      { title: "Result Publication", description: "TU FOM publishes the merit list based on entrance exam scores on the official website." },
      { title: "Campus & Program Selection", description: "Candidates select their preferred campuses and programs online based on their rank." },
      { title: "Admission Confirmation", description: "Visit the allotted campus with original documents, pay the first semester fees, and confirm admission." },
    ],
    admitCardInfo: "The CMAT admit card is mandatory for exam entry. Download it from the TU FOM admission portal after the release date. Ensure all details are correct before printing.",
    upcomingDates: [
      { date: "Shrawan 1 - Bhadra 15, 2082", event: "CMAT 2081 Registration", status: "Upcoming" },
      { date: "Bhadra 2082", event: "CMAT Entrance Examination Date" },
    ],
    pastDates: [
      { date: "Bhadra 10, 2081", event: "CMAT 2080 Examination" },
      { date: "Shrawan 1 - 25, 2081", event: "CMAT 2080 Registration" },
    ],
    faqs: [
      { question: "Can I apply for multiple management programs with one CMAT form?", answer: "Yes, a single CMAT score is valid for all management programs (BBA, BBM, BBS, BIM) under TU." },
      { question: "Is there negative marking in CMAT?", answer: "No, there is no negative marking in CMAT. Each correct answer carries 1 mark." },
      { question: "What is the application fee for CMAT?", answer: "The application fee is NPR 3,000 for regular applicants and NPR 4,500 for late applicants." },
      { question: "Which campuses accept CMAT scores?", answer: "All TU constituent campuses (Kirtipur, Shankar Dev, etc.) and affiliated colleges offering management programs accept CMAT scores." },
    ],
  },
  "kuumatt-2081": {
    id: "kuumatt-2081",
    title: "KUUMAT (Management Entrance) 2081",
    university: "Kathmandu University",
    faculty: "School of Management",
    status: "Upcoming",
    examDate: "TBA",
    nepaliDate: "TBA",
    imageUrl: "https://images.unsplash.com/photo-1523240682740-8f563509fa0a?auto=format&fit=crop&w=800&q=80",
    registrationStart: "TBA",
    registrationEnd: "TBA",
    examLevel: "University Level",
    duration: "2 Hours",
    questionType: "Multiple Choice (MCQ)",
    description: "KUUMAT (Kathmandu University Undergraduate Management Admission Test) is conducted by the School of Management, Kathmandu University for admission into BBA, BBA-Finance, and other management programs at KU.",
    conductingBody: "School of Management, Kathmandu University",
    examFrequency: "Once a year",
    examMode: "Computer Based Test (CBT)",
    applicationFee: "NPR 3,500",
    foreignFee: "USD 50",
    applicationSteps: [
      { title: "Fee Payment", description: "Pay the examination fee through eSewa, Khalti, ConnectIPS, or designated bank branches. Applicants: NPR 3,500 | Foreign applicants: USD 50." },
      { title: "Online Registration", description: "Visit the KU admission portal (ku.edu.np) and fill in personal details, academic records, and upload a passport-size photograph." },
      { title: "Document Upload & Submission", description: "Upload scanned copies of SEE, +2 transcripts, citizenship certificate, and character certificate. Submit the form and print the confirmation page." },
    ],
    eligibility: [
      { title: "Academic Qualification", description: "Must have passed 10+2 or equivalent in any stream from a recognized board." },
      { title: "Minimum Marks Requirement", description: "Must have secured a minimum of 50% marks or CGPA 2.0 in aggregate in +2 or equivalent examination." },
      { title: "Nationality", description: "Nepalese citizens and foreign nationals are eligible. Foreign candidates must provide equivalence certificate from NEB." },
    ],
    examPattern: [
      { label: "Total Questions", value: "100 MCQs" },
      { label: "Total Marks", value: "100" },
      { label: "Duration", value: "2 Hours" },
      { label: "Marking Scheme", value: "+1 Correct, -0.25 Incorrect" },
    ],
    subjectMarks: [
      { subject: "English Language", marks: 25 },
      { subject: "Mathematics", marks: 25 },
      { subject: "Logical Reasoning", marks: 25 },
      { subject: "General Knowledge", marks: 15 },
      { subject: "Computer Awareness", marks: 10 },
    ],
    modelSets: [
      { title: "KUUMAT Official Model Question 2080", size: "1.2 MB", description: "Complete 100 Questions with Blueprint" },
      { title: "KUUMAT 2080 Past Paper", size: "1.8 MB", description: "With Answer Keys" },
    ],
    courses: ["BBA", "BBA-Finance", "BBA-International Business", "BBM"],
    admissionSteps: [
      { title: "Result Publication", description: "KU SOM publishes the merit list based on entrance exam scores on the official website." },
      { title: "Interview/Group Discussion", description: "Shortlisted candidates are called for interview or group discussion rounds." },
      { title: "Final Admission", description: "Selected candidates visit the KU campus with original documents, pay the fees, and confirm admission." },
    ],
    admitCardInfo: "The KUUMAT admit card is mandatory for exam entry. Download it from the KU admission portal after the release date. Ensure all details are correct before printing.",
    upcomingDates: [
      { date: "TBA", event: "KUUMAT 2081 Registration", status: "Upcoming" },
      { date: "TBA", event: "KUUMAT Entrance Examination Date" },
    ],
    pastDates: [
      { date: "Ashwin 5, 2081", event: "KUUMAT 2080 Examination" },
      { date: "Bhadra 1 - 20, 2081", event: "KUUMAT 2080 Registration" },
    ],
    faqs: [
      { question: "Is KUUMAT conducted online or offline?", answer: "KUUMAT is conducted as a Computer Based Test (CBT) at designated test centers." },
      { question: "Is there negative marking in KUUMAT?", answer: "Yes, there is a negative marking of 0.25 marks for each incorrect answer." },
      { question: "What is the application fee for KUUMAT?", answer: "The application fee is NPR 3,500 for Nepalese students and USD 50 for foreign students." },
      { question: "Does KUUMAT have an interview round?", answer: "Yes, shortlisted candidates based on the entrance score are called for an interview or group discussion round." },
    ],
  },
};
