export { default as InstitutionLayout } from "./InstitutionLayout";
export * from "./InstitutionLayout";
export { default as OverviewPage } from "./OverviewPage";
export { default as AdmissionPage } from "./AdmissionPage";
export { default as AdmissionManagePage } from "./AdmissionManagePage";
export { default as ProgramPage } from "./ProgramPage";
export { default as CollegeProfilePage } from "./CollegeProfilePage";
export { default as CounsellingPage } from "./CounsellingPage";
export { default as EntrancePage } from "./EntrancePage";
export { default as EventsPage } from "./EventsPage";
export { default as NewsNoticePage } from "./NewsNoticePage";
export { default as QMSPage } from "./QMSPage";
export { default as ScholarshipSectionContainer } from "./ScholarshipSectionContainer";
